### ISSUE TITLE
OperationalError at /market/create/

### ISSUE THREAD

**Issue by kylmpap** [AlexDolls/DjangoAuctionApp#7]
When creating a new auction get error.(may be my mistake, am a newbie, waiting for a solution, Thanks)

OperationalError
**Error 11001 connecting to redis:6379. getaddrinfo failed.**

**Comment by AlexDolls** [comment]
@kylmpap Hey, glad to see you on my repo :)
https://stackoverflow.com/questions/8754304/redis-connection-to-127-0-0-16379-failed-connect-econnrefused
Maybe your redis-server is not running, try to check if you've correctly deployed the project.
P.S.
This project, actually, was created by me during learning process and there are was used not rly best-practice techniques that are exists for python in nowdays, so I strongly reccommend you since you're a newbee to google some roadmap for Python-Django, that will show you what to learn and in which order.
[https://roadmap.sh/python](https://roadmap.sh/python)
Honestly wish you successful learning!
